---
repos:
  - repo: https://github.com/python/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=magent
          - --skip=*.css,*.js,*.map,*.scss,*svg
          - --exclude-file=./README.md
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - '--per-file-ignores=*/__init__.py:F401'
          - --extend-ignore=E203
          - --max-complexity=205
          - --max-line-length=300
          - --show-source
          - --statistics
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus", "--keep-runtime-typing"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --source
          - --explain
          - --convention=google
          - --count
        exclude: "__init__.py"
        additional_dependencies: ["toml"]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ["pyright"]
